### ISSUE TITLE
Digraph building fails when Trait are involved

### ISSUE THREAD

**Issue by Trismegiste** [Trismegiste/Mondrian#28]
Trait are not parsed but method within trait are parsed.

Therefore they are added by ReflectionContext with an empty FQCN and generation fails at the digraph building (the second pass)

Need to process trait, at least, skip them in the first time

**Comment by CMCDragonkai** [comment]
Any news on this front? I would like to use Mondrian, but I was planning to use Traits as well.

**Comment by Trismegiste** [comment]
currently work in progress

**Comment by Trismegiste** [comment]
Alpha release at https://github.com/Trismegiste/Mondrian/releases/tag/v1.3.0-dev

**Comment by Trismegiste** [comment]
missing doc and some tests but it's no longer crash

https://github.com/Trismegiste/Mondrian/releases/tag/v1.3.1
