### ISSUE TITLE
Version 1.2 is not available on Packagist

### ISSUE THREAD

**Issue by CMCDragonkai** [Trismegiste/Mondrian#29]
Some of the versions are missing in packagist? https://packagist.org/packages/trismegiste/mondrian

Only 1.1.0 is available.

**Comment by Trismegiste** [comment]
that's odd, I've forced update and packagist doesn't add my 1.2 tag

**Comment by Trismegiste** [comment]
there was a conflict between composer.json and my own tag. I'm not a packagist expert

**Comment by Trismegiste** [comment]
added a new tag
