### ISSUE TITLE
warnings and notices

### ISSUE THREAD

**Issue by dwenaus** [Trismegiste/Mondrian#30]
I'm using php 5.5 and getting:
Warning: Invalid argument supplied for foreach() in /Mondrian/Transform/ReflectionContext.php on line 65

Warning: Invalid argument supplied for foreach() in /Mondrian/Transform/ReflectionContext.php on line 65

Catchable fatal error: Argument 1 passed to Trismegiste\Mondrian\Graph\Digraph::addEdge() must be an instance of Trismegiste\Mondrian\Graph\Vertex, null given, called in /Mondrian/Visitor/EdgeCollector.php on line 107 and defined in /Mondrian/Graph/Digraph.php on line 59

**Comment by dwenaus** [comment]
perhaps this package is not aware of traits?

**Comment by Trismegiste** [comment]
yes there is already a ticket. Now I struggle how to conceptualize trait in the grammar I've created. 
I think I can achieve soon a solution
