### ISSUE TITLE
Are "@var" for variables supported

### ISSUE THREAD

**Issue by aik099** [Trismegiste/Mondrian#31]
In my project a class factory is used to create objects. This means, that in the code I have `Factory::create('someName')` and `Factory::create('someOtherName')`, which indirectly maps to actual object class, that will be created.

To make IDE auto-complete work I do this:

``` php
/** @var ActualClassName $object */
$object = Factory::create('someName');
```

Are such `@var` annotations being processed?

**Comment by Trismegiste** [comment]
Hello

sorry no support for @var. I've thought about that but not implemented for two reasons : 
- a project with @var is usually well-coded and doesn't require Mondrian
- the comment could be wrong/deprecated. That's why I prefer to have false vertices than loosing one.

:beers:

**Comment by aik099** [comment]
I see. That is sad to hear. I wasn't able to understand much of graphs produced by this library anyway :wink:
